export const ApiMap = new Map ([
	['Bhutan', { Slug: 'bhutan', Population: 772 }],
  ['Bolivia', { Slug: 'bolivia', Population: 11673}],
  ['Burkina Faso', { Slug: 'burkina-faso', Population: 20903 }],
  ['Guinea-Bissau', { Slug: 'guinea-bissau', Population: 1968 }],
  ['Mongolia', { Slug: 'mongolia', Population: 3278 }],
  ['Niue', { Slug: 'niue', Population: 2 }],
  ['Japan', { Slug: 'japan', Population: 126476 }],
  ['Saint Helena', { Slug: 'saint-helena', Population: 6 }],
  ['Ukraine', { Slug: 'ukraine', Population: 43734 }],
  ['Albania', { Slug: 'albania', Population: 2878 }],
  ['Australia', { Slug: 'australia', Population: 25500 }],
  ['Korea (South)', { Slug: 'korea-south', Population: 51269}],
  ['Liberia', { Slug: 'liberia', Population: 5058 }],
  ['Tajikistan', { Slug: 'tajikistan', Population: 9538 }],
  ['Tuvalu', { Slug: 'tuvalu', Population: 12 }],
  ['South Georgia and the South Sandwich Islands', { Slug: 'south-georgia-and-the-south-sandwich-islands',
    Population: null }],
  ['Antarctica', { Slug: 'antarctica', Population: null }],
  ['Montserrat', { Slug: 'montserrat', Population: 5 }],
  ['Northern Mariana Islands', { Slug: 'northern-mariana-islands', Population: 58 }],
  ['Poland', { Slug: 'poland', Population: 37847 }],
  ['Portugal', { Slug: 'portugal', Population: 10197 }],
  ['Switzerland', { Slug: 'switzerland', Population: 8655 }],
  ['Uruguay', { Slug: 'uruguay', Population: 3474 }],
  ['American Samoa', { Slug: 'american-samoa', Population: 55 }],
  ['Guadeloupe', { Slug: 'guadeloupe', Population: 400 }],
  ['Iraq', { Slug: 'iraq', Population: 40223 }],
  ['Jamaica', { Slug: 'jamaica', Population: 2961 }],
  ['Burundi', { Slug: 'burundi', Population: 11891 }],
  ['Chad', { Slug: 'chad', Population: 16426 }],
  ['Guam', { Slug: 'guam', Population: 169 }],
  ['Saint-Barthélemy', { Slug: 'saint-barthélemy', Population: 10}],
  ['Sri Lanka', { Slug: 'sri-lanka', Population: 21413 }],
  ['Gibraltar', { Slug: 'gibraltar', Population: 34 }],
  ['Pitcairn', { Slug: 'pitcairn', Population: null }],
  ['Slovenia', { Slug: 'slovenia', Population: 2079 }],
  ['Timor-Leste', { Slug: 'timor-leste', Population: 1318 }],
  ['Azerbaijan', { Slug: 'azerbaijan', Population: 10139 }],
  ['Central African Republic', { Slug: 'central-african-republic', Population: 4830 }],
  ['Jordan', { Slug: 'jordan', Population: 10203 }],
  ['Pakistan', { Slug: 'pakistan', Population: 220892 }],
  ['Morocco', { Slug: 'morocco', Population: 36911 }],
  ['Uzbekistan', { Slug: 'uzbekistan', Population: 33469 }],
  ['Eritrea', { Slug: 'eritrea', Population: 3546 }],
  ['Kenya', { Slug: 'kenya', Population: 53771 }],
  ['Dominican Republic', { Slug: 'dominican-republic', Population: 10848 }],
  ['French Southern Territories', { Slug: 'french-southern-territories', Population: null }],
  ['Montenegro', { Slug: 'montenegro', Population: 628 }],
  ['Croatia', { Slug: 'croatia', Population: 4105 }],
  ['Guernsey', { Slug: 'guernsey', Population: null }],
  ['Moldova', { Slug: 'moldova', Population: 4034}],
  ['Mozambique', { Slug: 'mozambique', Population: 31255 }],
  ['Côte d\'Ivoire', { Slug: 'cote-divoire', Population: 26378 }],
  ['Palestinian Territory', { Slug: 'palestine', Population: 5101}],
  ['United Arab Emirates', { Slug: 'united-arab-emirates', Population: 9890 }],
  ['Costa Rica', { Slug: 'costa-rica', Population: 5094 }],
  ['Haiti', { Slug: 'haiti', Population: 11403 }],
  ['Malawi', { Slug: 'malawi', Population: 19130 }],
  ['Puerto Rico', { Slug: 'puerto-rico', Population: 2861 }],
  ['Cape Verde', { Slug: 'cape-verde', Population: 556}],
  ['Congo (Brazzaville)', { Slug: 'congo-brazzaville', Population: 5518}],
  ['Panama', { Slug: 'panama', Population: 4315 }],
  ['Serbia', { Slug: 'serbia', Population: 8737 }],
  ['Brunei Darussalam', { Slug: 'brunei', Population: 437 }],
  ['China', { Slug: 'china', Population: 1439324 }],
  ['Guinea', { Slug: 'guinea', Population: 13133 }],
  ['Iceland', { Slug: 'iceland', Population: 341 }],
  ['Luxembourg', { Slug: 'luxembourg', Population: 626 }],
  ['Romania', { Slug: 'romania', Population: 19238 }],
  ['Saint Lucia', { Slug: 'saint-lucia', Population: 184 }],
  ['Antigua and Barbuda', { Slug: 'antigua-and-barbuda', Population: 98 }],
  ['Ghana', { Slug: 'ghana', Population: 31073 }],
  ['Netherlands Antilles', { Slug: 'netherlands-antilles', Population: 17135}],
  ['Qatar', { Slug: 'qatar', Population: 2881 }],
  ['Yemen', { Slug: 'yemen', Population: 29826 }],
  ['Guyana', { Slug: 'guyana', Population: 787 }],
  ['Honduras', { Slug: 'honduras', Population: 9905 }],
  ['Réunion', { Slug: 'réunion', Population: 895 }],
  ['Saint Kitts and Nevis', { Slug: 'saint-kitts-and-nevis', Population: 53 }],
  ['Djibouti', { Slug: 'djibouti', Population: 988 }],
  ['Hong Kong, SAR China', { Slug: 'hong-kong-sar-china', Population: 7497}],
  ['Samoa', { Slug: 'samoa', Population: 198 }],
  ['Solomon Islands', { Slug: 'solomon-islands', Population: 687 }],
  ['Korea (North)', { Slug: 'korea-north', Population: 25779}],
  ['Nauru', { Slug: 'nauru', Population: 11 }],
  ['Norway', { Slug: 'norway', Population: 5421 }],
  ['Papua New Guinea', { Slug: 'papua-new-guinea', Population: 8947 }],
  ['Turks and Caicos Islands', { Slug: 'turks-and-caicos-islands', Population: 39 }],
  ['Heard and Mcdonald Islands', { Slug: 'heard-and-mcdonald-islands', Population: null }],
  ['India', { Slug: 'india', Population: 1380004 }],
  ['Rwanda', { Slug: 'rwanda', Population: 12952 }],
  ['Cook Islands', { Slug: 'cook-islands', Population: 18 }],
  ['Ethiopia', { Slug: 'ethiopia', Population: 114964 }],
  ['Fiji', { Slug: 'fiji', Population: 896 }],
  ['Isle of Man', { Slug: 'isle-of-man', Population: 85 }],
  ['Swaziland', { Slug: 'swaziland', Population: 8655}],
  ['Bahrain', { Slug: 'bahrain', Population: 1702 }],
  ['Bosnia and Herzegovina', { Slug: 'bosnia-and-herzegovina', Population: 3281 }],
  ['Canada', { Slug: 'canada', Population: 37742 }],
  ['Germany', { Slug: 'germany', Population: 83784 }],
  ['Liechtenstein', { Slug: 'liechtenstein', Population: 38 }],
  ['Argentina', { Slug: 'argentina', Population: 45196 }],
  ['Holy See (Vatican City State)', { Slug: 'holy-see-vatican-city-state', Population: null }],
  ['Singapore', { Slug: 'singapore', Population: 5850 }],
  ['Tanzania, United Republic of', { Slug: 'tanzania', Population: 59734}],
  ['Western Sahara', { Slug: 'western-sahara', Population: 597 }],
  ['United Kingdom', { Slug: 'united-kingdom', Population: 67886 }],
  ['ALA Aland Islands', { Slug: 'ala-aland-islands', Population: null }],
  ['Bermuda', { Slug: 'bermuda', Population: 62 }],
  ['Christmas Island', { Slug: 'christmas-island', Population: null }],
  ['Nigeria', { Slug: 'nigeria', Population: 206140 }],
  ['Slovakia', { Slug: 'slovakia', Population: 5460 }],
  ['Trinidad and Tobago', { Slug: 'trinidad-and-tobago', Population: 1399 }],
  ['Botswana', { Slug: 'botswana', Population: 2352 }],
  ['El Salvador', { Slug: 'el-salvador', Population: 6486 }],
  ['Namibia', { Slug: 'namibia', Population: 2541 }],
  ['Saint Vincent and Grenadines', { Slug: 'saint-vincent-and-the-grenadines', Population: 111}],
  ['Brazil', { Slug: 'brazil', Population: 212559 }],
  ['Guatemala', { Slug: 'guatemala', Population: 17916 }],
  ['Kazakhstan', { Slug: 'kazakhstan', Population: 18777 }],
  ['Niger', { Slug: 'niger', Population: 24207 }],
  ['Finland', { Slug: 'finland', Population: 5541 }],
  ['French Polynesia', { Slug: 'french-polynesia', Population: 281 }],
  ['Israel', { Slug: 'israel', Population: 8656 }],
  ['Belarus', { Slug: 'belarus', Population: 9449 }],
  ['Chile', { Slug: 'chile', Population: 19116 }],
  ['Mayotte', { Slug: 'mayotte', Population: 273 }],
  ['British Virgin Islands', { Slug: 'british-virgin-islands', Population: 30 }],
  ['Estonia', { Slug: 'estonia', Population: 1327 }],
  ['Ireland', { Slug: 'ireland', Population: 4938 }],
  ['Russian Federation', { Slug: 'russia', Population: 145934 }],
  ['Somalia', { Slug: 'somalia', Population: 15893 }],
  ['Czech Republic', { Slug: 'czech-republic', Population: 10709}],
  ['Philippines', { Slug: 'philippines', Population: 109581 }],
  ['Uganda', { Slug: 'uganda', Population: 45741 }],
  ['Aruba', { Slug: 'aruba', Population: 107 }],
  ['Cocos (Keeling) Islands', { Slug: 'cocos-keeling-islands', Population: null }],
  ['Hungary', { Slug: 'hungary', Population: 9660 }],
  ['San Marino', { Slug: 'san-marino', Population: 34 }],
  ['Cayman Islands', { Slug: 'cayman-islands', Population: 66 }],
  ['Equatorial Guinea', { Slug: 'equatorial-guinea', Population: 1403 }],
  ['Lao PDR', { Slug: 'lao-pdr', Population: 7276}],
  ['Myanmar', { Slug: 'myanmar', Population: 54410 }],
  ['Norfolk Island', { Slug: 'norfolk-island', Population: null }],
  ['Oman', { Slug: 'oman', Population: 5107 }],
  ['British Indian Ocean Territory', { Slug: 'british-indian-ocean-territory', Population: null }],
  ['Libya', { Slug: 'libya', Population: 6871 }],
  ['Republic of Kosovo', { Slug: 'kosovo', Population: null }],
  ['Venezuela (Bolivarian Republic)', { Slug: 'venezuela', Population: 28436}],
  ['Malaysia', { Slug: 'malaysia', Population: 32366 }],
  ['Palau', { Slug: 'palau', Population: 18 }],
  ['Spain', { Slug: 'spain', Population: 46755 }],
  ['Zambia', { Slug: 'zambia', Population: 18384 }],
  ['Austria', { Slug: 'austria', Population: 9006 }],
  ['Bangladesh', { Slug: 'bangladesh', Population: 164689 }],
  ['New Zealand', { Slug: 'new-zealand', Population: 4822 }],
  ['Dominica', { Slug: 'dominica', Population: 72 }],
  ['Falkland Islands (Malvinas)', { Slug: 'falkland-islands-malvinas', Population: 3 }],
  ['France', { Slug: 'france', Population: 65274 }],
  ['Madagascar', { Slug: 'madagascar', Population: 27691 }],
  ['Micronesia, Federated States of', { Slug: 'micronesia', Population: null }],
  ['Saudi Arabia', { Slug: 'saudi-arabia', Population: 34814 }],
  ['Comoros', { Slug: 'comoros', Population: 870 }],
  ['Seychelles', { Slug: 'seychelles', Population: 98 }],
  ['Svalbard and Jan Mayen Islands', { Slug: 'svalbard-and-jan-mayen-islands', Population: null }],
  ['Bahamas', { Slug: 'bahamas', Population: 393 }],
  ['Italy', { Slug: 'italy', Population: 60462 }],
  ['Mauritius', { Slug: 'mauritius', Population: 1272 }],
  ['Saint-Martin (French part)', { Slug: 'saint-martin-french-part', Population: null }],
  ['New Caledonia', { Slug: 'new-caledonia', Population: 285 }],
  ['Andorra', { Slug: 'andorra', Population: 77 }],
  ['Gambia', { Slug: 'gambia', Population: 2417 }],
  ['Grenada', { Slug: 'grenada', Population: 113 }],
  ['Monaco', { Slug: 'monaco', Population: 39 }],
  ['Nepal', { Slug: 'nepal', Population: 29137 }],
  ['Armenia', { Slug: 'armenia', Population: 2963 }],
  ['French Guiana', { Slug: 'french-guiana', Population: 299 }],
  ['Saint Pierre and Miquelon', { Slug: 'saint-pierre-and-miquelon', Population: 6 }],
  ['Vanuatu', { Slug: 'vanuatu', Population: 307 }],
  ['Tunisia', { Slug: 'tunisia', Population: 11819 }],
  ['Cambodia', { Slug: 'cambodia', Population: 16719 }],
  ['Cyprus', { Slug: 'cyprus', Population: 1207 }],
  ['Indonesia', { Slug: 'indonesia', Population: 273524 }],
  ['Kuwait', { Slug: 'kuwait', Population: 4271 }],
  ['Kyrgyzstan', { Slug: 'kyrgyzstan', Population: 6524 }],
  ['Sudan', { Slug: 'sudan', Population: 43849 }],
  ['Greece', { Slug: 'greece', Population: 10423 }],
  ['Mauritania', { Slug: 'mauritania', Population: 4650 }],
  ['Senegal', { Slug: 'senegal', Population: 16744 }],
  ['Sweden', { Slug: 'sweden', Population: 10099 }],
  ['Angola', { Slug: 'angola', Population: 32866 }],
  ['Latvia', { Slug: 'latvia', Population: 1886 }],
  ['Lebanon', { Slug: 'lebanon', Population: 6825 }],
  ['Malta', { Slug: 'malta', Population: 442 }],
  ['Martinique', { Slug: 'martinique', Population: 375 }],
  ['Congo (Kinshasa)', { Slug: 'congo-kinshasa', Population: 5518}],
  ['Georgia', { Slug: 'georgia', Population: 3989 }],
  ['Sierra Leone', { Slug: 'sierra-leone', Population: 7977 }],
  ['United States of America', { Slug: 'united-states', Population: 331003 }],
  ['Ecuador', { Slug: 'ecuador', Population: 17643 }],
  ['Jersey', { Slug: 'jersey', Population: null }],
  ['Algeria', { Slug: 'algeria', Population: 43851 }],
  ['South Africa', { Slug: 'south-africa', Population: 59309 }],
  ['Barbados', { Slug: 'barbados', Population: 287 }],
  ['Bouvet Island', { Slug: 'bouvet-island', Population: null }],
  ['Colombia', { Slug: 'colombia', Population: 50883 }],
  ['Syrian Arab Republic (Syria)', { Slug: 'syria', Population: 17501}],
  ['Belgium', { Slug: 'belgium', Population: 11590 }],
  ['Mexico', { Slug: 'mexico', Population: 128933 }],
  ['US Minor Outlying Islands', { Slug: 'us-minor-outlying-islands', Population: null }],
  ['Taiwan, Republic of China', { Slug: 'taiwan', Population: 23817}],
  ['Faroe Islands', { Slug: 'faroe-islands', Population: 49 }],
  ['Iran, Islamic Republic of', { Slug: 'iran', Population: 83993}],
  ['Peru', { Slug: 'peru', Population: 32972 }],
  ['Thailand', { Slug: 'thailand', Population: 69800 }],
  ['Togo', { Slug: 'togo', Population: 8279 }],
  ['Belize', { Slug: 'belize', Population: 398 }],
  ['Denmark', { Slug: 'denmark', Population: 5792 }],
  ['Egypt', { Slug: 'egypt', Population: 102334 }],
  ['Gabon', { Slug: 'gabon', Population: 2226 }],
  ['Paraguay', { Slug: 'paraguay', Population: 7133 }],
  ['Turkmenistan', { Slug: 'turkmenistan', Population: 6031 }],
  ['Kiribati', { Slug: 'kiribati', Population: 119 }],
  ['Virgin Islands, US', { Slug: 'virgin-islands', Population: null }],
  ['Zimbabwe', { Slug: 'zimbabwe', Population: 14863 }],
  ['Tokelau', { Slug: 'tokelau', Population: 1 }],
  ['Benin', { Slug: 'benin', Population: 12123 }],
  ['Lesotho', { Slug: 'lesotho', Population: 2142 }],
  ['Macedonia, Republic of', { Slug: 'macedonia', Population: 2083}],
  ['Mali', { Slug: 'mali', Population: 20251 }],
  ['Marshall Islands', { Slug: 'marshall-islands', Population: 59 }],
  ['Sao Tome and Principe', { Slug: 'sao-tome-and-principe', Population: 219 }],
  ['South Sudan', { Slug: 'south-sudan', Population: 11194 }],
  ['Turkey', { Slug: 'turkey', Population: 84339 }],
  ['Afghanistan', { Slug: 'afghanistan', Population: 38928 }],
  ['Lithuania', { Slug: 'lithuania', Population: 2722 }],
  ['Nicaragua', { Slug: 'nicaragua', Population: 6625 }],
  ['Suriname', { Slug: 'suriname', Population: 587 }],
  ['Tonga', { Slug: 'tonga', Population: 106 }],
  ['Macao, SAR China', { Slug: 'macao-sar-china', Population: 649}],
  ['Wallis and Futuna Islands', { Slug: 'wallis-and-futuna-islands', Population: 11 }],
  ['Maldives', { Slug: 'maldives', Population: 541 }],
  ['Netherlands', { Slug: 'netherlands', Population: 17135 }],
  ['Anguilla', { Slug: 'anguilla', Population: 15 }],
  ['Bulgaria', { Slug: 'bulgaria', Population: 6948 }],
  ['Cuba', { Slug: 'cuba', Population: 11327 }],
  ['Greenland', { Slug: 'greenland', Population: 57 }],
  ['Cameroon', { Slug: 'cameroon', Population: 26546 }],
  ['Viet Nam', { Slug: 'vietnam', Population: 97339 }]
])