export const CountryArr = [
  { Country: 'ALA Aland Islands', Slug: 'ala-aland-islands', Population: null },
  { Country: 'Afghanistan', Slug: 'afghanistan', Population: 38928 },
  { Country: 'Albania', Slug: 'albania', Population: 2878 },
  { Country: 'Algeria', Slug: 'algeria', Population: 43851 },
  { Country: 'American Samoa', Slug: 'american-samoa', Population: 55 },
  { Country: 'Andorra', Slug: 'andorra', Population: 77 },
  { Country: 'Angola', Slug: 'angola', Population: 32866 },
  { Country: 'Anguilla', Slug: 'anguilla', Population: 15 },
  { Country: 'Antarctica', Slug: 'antarctica', Population: null },
  { Country: 'Antigua and Barbuda', Slug: 'antigua-and-barbuda', Population: 98 },
  { Country: 'Argentina', Slug: 'argentina', Population: 45196 },
  { Country: 'Armenia', Slug: 'armenia', Population: 2963 },
  { Country: 'Aruba', Slug: 'aruba', Population: 107 },
  { Country: 'Australia', Slug: 'australia', Population: 25500 },
  { Country: 'Austria', Slug: 'austria', Population: 9006 },
  { Country: 'Azerbaijan', Slug: 'azerbaijan', Population: 10139 },
  { Country: 'Bahamas', Slug: 'bahamas', Population: 393 },
  { Country: 'Bahrain', Slug: 'bahrain', Population: 1702 },
  { Country: 'Bangladesh', Slug: 'bangladesh', Population: 164689 },
  { Country: 'Barbados', Slug: 'barbados', Population: 287 },
  { Country: 'Belarus', Slug: 'belarus', Population: 9449 },
  { Country: 'Belgium', Slug: 'belgium', Population: 11590 },
  { Country: 'Belize', Slug: 'belize', Population: 398 },
  { Country: 'Benin', Slug: 'benin', Population: 12123 },
  { Country: 'Bermuda', Slug: 'bermuda', Population: 62 },
  { Country: 'Bhutan', Slug: 'bhutan', Population: 772 },
  { Country: 'Bolivia', Slug: 'bolivia', Population: 11673 },
  { Country: 'Bosnia and Herzegovina', Slug: 'bosnia-and-herzegovina', Population: 3281 },
  { Country: 'Botswana', Slug: 'botswana', Population: 2352 },
  { Country: 'Bouvet Island', Slug: 'bouvet-island', Population: null },
  { Country: 'Brazil', Slug: 'brazil', Population: 212559 },
  { Country: 'British Indian Ocean Territory', Slug: 'british-indian-ocean-territory', Population: null },
  { Country: 'British Virgin Islands', Slug: 'british-virgin-islands', Population: 30 },
  { Country: 'Brunei Darussalam', Slug: 'brunei', Population: 437 },
  { Country: 'Bulgaria', Slug: 'bulgaria', Population: 6948 },
  { Country: 'Burkina Faso', Slug: 'burkina-faso', Population: 20903 },
  { Country: 'Burundi', Slug: 'burundi', Population: 11891 },
  { Country: 'Cambodia', Slug: 'cambodia', Population: 16719 },
  { Country: 'Cameroon', Slug: 'cameroon', Population: 26546 },
  { Country: 'Canada', Slug: 'canada', Population: 37742 },
  { Country: 'Cape Verde', Slug: 'cape-verde', Population: 556 },
  { Country: 'Cayman Islands', Slug: 'cayman-islands', Population: 66 },
  { Country: 'Central African Republic', Slug: 'central-african-republic', Population: 4830 },
  { Country: 'Chad', Slug: 'chad', Population: 16426 },
  { Country: 'Chile', Slug: 'chile', Population: 19116 },
  { Country: 'China', Slug: 'china', Population: 1439324 },
  { Country: 'Christmas Island', Slug: 'christmas-island', Population: null },
  { Country: 'Cocos (Keeling) Islands', Slug: 'cocos-keeling-islands', Population: null },
  { Country: 'Colombia', Slug: 'colombia', Population: 50883 },
  { Country: 'Comoros', Slug: 'comoros', Population: 870 },
  { Country: 'Congo (Brazzaville)', Slug: 'congo-brazzaville', Population: 5518 },
  { Country: 'Congo (Kinshasa)', Slug: 'congo-kinshasa', Population: 5518 },
  { Country: 'Cook Islands', Slug: 'cook-islands', Population: 18 },
  { Country: 'Costa Rica', Slug: 'costa-rica', Population: 5094 },
  { Country: 'Croatia', Slug: 'croatia', Population: 4105 },
  { Country: 'Cuba', Slug: 'cuba', Population: 11327 },
  { Country: 'Cyprus', Slug: 'cyprus', Population: 1207 },
  { Country: 'Czech Republic', Slug: 'czech-republic', Population: 10709 },
  { Country: 'Côte d\'Ivoire', Slug: 'cote-divoire', Population: 26378 },
  { Country: 'Denmark', Slug: 'denmark', Population: 5792 },
  { Country: 'Djibouti', Slug: 'djibouti', Population: 988 },
  { Country: 'Dominica', Slug: 'dominica', Population: 72 },
  { Country: 'Dominican Republic', Slug: 'dominican-republic', Population: 10848 },
  { Country: 'Ecuador', Slug: 'ecuador', Population: 17643 },
  { Country: 'Egypt', Slug: 'egypt', Population: 102334 },
  { Country: 'El Salvador', Slug: 'el-salvador', Population: 6486 },
  { Country: 'Equatorial Guinea', Slug: 'equatorial-guinea', Population: 1403 },
  { Country: 'Eritrea', Slug: 'eritrea', Population: 3546 },
  { Country: 'Estonia', Slug: 'estonia', Population: 1327 },
  { Country: 'Ethiopia', Slug: 'ethiopia', Population: 114964 },
  { Country: 'Falkland Islands (Malvinas)', Slug: 'falkland-islands-malvinas', Population: 3 },
  { Country: 'Faroe Islands', Slug: 'faroe-islands', Population: 49 },
  { Country: 'Fiji', Slug: 'fiji', Population: 896 },
  { Country: 'Finland', Slug: 'finland', Population: 5541 },
  { Country: 'France', Slug: 'france', Population: 65274 },
  { Country: 'French Guiana', Slug: 'french-guiana', Population: 299 },
  { Country: 'French Polynesia', Slug: 'french-polynesia', Population: 281 },
  { Country: 'French Southern Territories', Slug: 'french-southern-territories', Population: null },
  { Country: 'Gabon', Slug: 'gabon', Population: 2226 },
  { Country: 'Gambia', Slug: 'gambia', Population: 2417 },
  { Country: 'Georgia', Slug: 'georgia', Population: 3989 },
  { Country: 'Germany', Slug: 'germany', Population: 83784 },
  { Country: 'Ghana', Slug: 'ghana', Population: 31073 },
  { Country: 'Gibraltar', Slug: 'gibraltar', Population: 34 },
  { Country: 'Greece', Slug: 'greece', Population: 10423 },
  { Country: 'Greenland', Slug: 'greenland', Population: 57 },
  { Country: 'Grenada', Slug: 'grenada', Population: 113 },
  { Country: 'Guadeloupe', Slug: 'guadeloupe', Population: 400 },
  { Country: 'Guam', Slug: 'guam', Population: 169 },
  { Country: 'Guatemala', Slug: 'guatemala', Population: 17916 },
  { Country: 'Guernsey', Slug: 'guernsey', Population: null },
  { Country: 'Guinea', Slug: 'guinea', Population: 13133 },
  { Country: 'Guinea-Bissau', Slug: 'guinea-bissau', Population: 1968 },
  { Country: 'Guyana', Slug: 'guyana', Population: 787 },
  { Country: 'Haiti', Slug: 'haiti', Population: 11403 },
  { Country: 'Heard and Mcdonald Islands', Slug: 'heard-and-mcdonald-islands', Population: null },
  { Country: 'Holy See (Vatican City State)', Slug: 'holy-see-vatican-city-state', Population: null },
  { Country: 'Honduras', Slug: 'honduras', Population: 9905 },
  { Country: 'Hong Kong, SAR China', Slug: 'hong-kong-sar-china', Population: 7497 },
  { Country: 'Hungary', Slug: 'hungary', Population: 9660 },
  { Country: 'Iceland', Slug: 'iceland', Population: 341 },
  { Country: 'India', Slug: 'india', Population: 1380004 },
  { Country: 'Indonesia', Slug: 'indonesia', Population: 273524 },
  { Country: 'Iran, Islamic Republic of', Slug: 'iran', Population: 83993 },
  { Country: 'Iraq', Slug: 'iraq', Population: 40223 },
  { Country: 'Ireland', Slug: 'ireland', Population: 4938 },
  { Country: 'Isle of Man', Slug: 'isle-of-man', Population: 85 },
  { Country: 'Israel', Slug: 'israel', Population: 8656 },
  { Country: 'Italy', Slug: 'italy', Population: 60462 },
  { Country: 'Jamaica', Slug: 'jamaica', Population: 2961 },
  { Country: 'Japan', Slug: 'japan', Population: 126476 },
  { Country: 'Jersey', Slug: 'jersey', Population: null },
  { Country: 'Jordan', Slug: 'jordan', Population: 10203 },
  { Country: 'Kazakhstan', Slug: 'kazakhstan', Population: 18777 },
  { Country: 'Kenya', Slug: 'kenya', Population: 53771 },
  { Country: 'Kiribati', Slug: 'kiribati', Population: 119 },
  { Country: 'Korea (North)', Slug: 'korea-north', Population: 25779 },
  { Country: 'Korea (South)', Slug: 'korea-south', Population: 51269 },
  { Country: 'Kuwait', Slug: 'kuwait', Population: 4271 },
  { Country: 'Kyrgyzstan', Slug: 'kyrgyzstan', Population: 6524 },
  { Country: 'Lao PDR', Slug: 'lao-pdr', Population: 7276 },
  { Country: 'Latvia', Slug: 'latvia', Population: 1886 },
  { Country: 'Lebanon', Slug: 'lebanon', Population: 6825 },
  { Country: 'Lesotho', Slug: 'lesotho', Population: 2142 },
  { Country: 'Liberia', Slug: 'liberia', Population: 5058 },
  { Country: 'Libya', Slug: 'libya', Population: 6871 },
  { Country: 'Liechtenstein', Slug: 'liechtenstein', Population: 38 },
  { Country: 'Lithuania', Slug: 'lithuania', Population: 2722 },
  { Country: 'Luxembourg', Slug: 'luxembourg', Population: 626 },
  { Country: 'Macao, SAR China', Slug: 'macao-sar-china', Population: 649 },
  { Country: 'Macedonia, Republic of', Slug: 'macedonia', Population: 2083 },
  { Country: 'Madagascar', Slug: 'madagascar', Population: 27691 },
  { Country: 'Malawi', Slug: 'malawi', Population: 19130 },
  { Country: 'Malaysia', Slug: 'malaysia', Population: 32366 },
  { Country: 'Maldives', Slug: 'maldives', Population: 541 },
  { Country: 'Mali', Slug: 'mali', Population: 20251 },
  { Country: 'Malta', Slug: 'malta', Population: 442 },
  { Country: 'Marshall Islands', Slug: 'marshall-islands', Population: 59 },
  { Country: 'Martinique', Slug: 'martinique', Population: 375 },
  { Country: 'Mauritania', Slug: 'mauritania', Population: 4650 },
  { Country: 'Mauritius', Slug: 'mauritius', Population: 1272 },
  { Country: 'Mayotte', Slug: 'mayotte', Population: 273 },
  { Country: 'Mexico', Slug: 'mexico', Population: 128933 },
  { Country: 'Micronesia, Federated States of', Slug: 'micronesia', Population: null },
  { Country: 'Moldova', Slug: 'moldova', Population: 4034 },
  { Country: 'Monaco', Slug: 'monaco', Population: 39 },
  { Country: 'Mongolia', Slug: 'mongolia', Population: 3278 },
  { Country: 'Montenegro', Slug: 'montenegro', Population: 628 },
  { Country: 'Montserrat', Slug: 'montserrat', Population: 5 },
  { Country: 'Morocco', Slug: 'morocco', Population: 36911 },
  { Country: 'Mozambique', Slug: 'mozambique', Population: 31255 },
  { Country: 'Myanmar', Slug: 'myanmar', Population: 54410 },
  { Country: 'Namibia', Slug: 'namibia', Population: 2541 },
  { Country: 'Nauru', Slug: 'nauru', Population: 11 },
  { Country: 'Nepal', Slug: 'nepal', Population: 29137 },
  { Country: 'Netherlands', Slug: 'netherlands', Population: 17135 },
  { Country: 'Netherlands Antilles', Slug: 'netherlands-antilles', Population: 17135 },
  { Country: 'New Caledonia', Slug: 'new-caledonia', Population: 285 },
  { Country: 'New Zealand', Slug: 'new-zealand', Population: 4822 },
  { Country: 'Nicaragua', Slug: 'nicaragua', Population: 6625 },
  { Country: 'Niger', Slug: 'niger', Population: 24207 },
  { Country: 'Nigeria', Slug: 'nigeria', Population: 206140 },
  { Country: 'Niue', Slug: 'niue', Population: 2 },
  { Country: 'Norfolk Island', Slug: 'norfolk-island', Population: null },
  { Country: 'Northern Mariana Islands', Slug: 'northern-mariana-islands', Population: 58 },
  { Country: 'Norway', Slug: 'norway', Population: 5421 },
  { Country: 'Oman', Slug: 'oman', Population: 5107 },
  { Country: 'Pakistan', Slug: 'pakistan', Population: 220892 },
  { Country: 'Palau', Slug: 'palau', Population: 18 },
  { Country: 'Palestinian Territory', Slug: 'palestine', Population: 5101 },
  { Country: 'Panama', Slug: 'panama', Population: 4315 },
  { Country: 'Papua New Guinea', Slug: 'papua-new-guinea', Population: 8947 },
  { Country: 'Paraguay', Slug: 'paraguay', Population: 7133 },
  { Country: 'Peru', Slug: 'peru', Population: 32972 },
  { Country: 'Philippines', Slug: 'philippines', Population: 109581 },
  { Country: 'Pitcairn', Slug: 'pitcairn', Population: null },
  { Country: 'Poland', Slug: 'poland', Population: 37847 },
  { Country: 'Portugal', Slug: 'portugal', Population: 10197 },
  { Country: 'Puerto Rico', Slug: 'puerto-rico', Population: 2861 },
  { Country: 'Qatar', Slug: 'qatar', Population: 2881 },
  { Country: 'Republic of Kosovo', Slug: 'kosovo', Population: null },
  { Country: 'Romania', Slug: 'romania', Population: 19238 },
  { Country: 'Russian Federation', Slug: 'russia', Population: 145934 },
  { Country: 'Rwanda', Slug: 'rwanda', Population: 12952 },
  { Country: 'Réunion', Slug: 'réunion', Population: 895 },
  { Country: 'Saint Helena', Slug: 'saint-helena', Population: 6 },
  { Country: 'Saint Kitts and Nevis', Slug: 'saint-kitts-and-nevis', Population: 53 },
  { Country: 'Saint Lucia', Slug: 'saint-lucia', Population: 184 },
  { Country: 'Saint Pierre and Miquelon', Slug: 'saint-pierre-and-miquelon', Population: 6 },
  { Country: 'Saint Vincent and Grenadines', Slug: 'saint-vincent-and-the-grenadines', Population: 111 },
  { Country: 'Saint-Barthélemy', Slug: 'saint-barthélemy', Population: 10 },
  { Country: 'Saint-Martin (French part)', Slug: 'saint-martin-french-part', Population: null },
  { Country: 'Samoa', Slug: 'samoa', Population: 198 },
  { Country: 'San Marino', Slug: 'san-marino', Population: 34 },
  { Country: 'Sao Tome and Principe', Slug: 'sao-tome-and-principe', Population: 219 },
  { Country: 'Saudi Arabia', Slug: 'saudi-arabia', Population: 34814 },
  { Country: 'Senegal', Slug: 'senegal', Population: 16744 },
  { Country: 'Serbia', Slug: 'serbia', Population: 8737 },
  { Country: 'Seychelles', Slug: 'seychelles', Population: 98 },
  { Country: 'Sierra Leone', Slug: 'sierra-leone', Population: 7977 },
  { Country: 'Singapore', Slug: 'singapore', Population: 5850 },
  { Country: 'Slovakia', Slug: 'slovakia', Population: 5460 },
  { Country: 'Slovenia', Slug: 'slovenia', Population: 2079 },
  { Country: 'Solomon Islands', Slug: 'solomon-islands', Population: 687 },
  { Country: 'Somalia', Slug: 'somalia', Population: 15893 },
  { Country: 'South Africa', Slug: 'south-africa', Population: 59309 },
  { Country: 'South Georgia and the South Sandwich Islands', Slug: 'south-georgia-and-the-south-sandwich-islands', Population: null },
  { Country: 'South Sudan', Slug: 'south-sudan', Population: 11194 },
  { Country: 'Spain', Slug: 'spain', Population: 46755 },
  { Country: 'Sri Lanka', Slug: 'sri-lanka', Population: 21413 },
  { Country: 'Sudan', Slug: 'sudan', Population: 43849 },
  { Country: 'Suriname', Slug: 'suriname', Population: 587 },
  { Country: 'Svalbard and Jan Mayen Islands', Slug: 'svalbard-and-jan-mayen-islands', Population: null },
  { Country: 'Swaziland', Slug: 'swaziland', Population: 8655 },
  { Country: 'Sweden', Slug: 'sweden', Population: 10099 },
  { Country: 'Switzerland', Slug: 'switzerland', Population: 8655 },
  { Country: 'Syrian Arab Republic (Syria)', Slug: 'syria', Population: 17501 },
  { Country: 'Taiwan, Republic of China', Slug: 'taiwan', Population: 23817 },
  { Country: 'Tajikistan', Slug: 'tajikistan', Population: 9538 },
  { Country: 'Tanzania, United Republic of', Slug: 'tanzania', Population: 59734 },
  { Country: 'Thailand', Slug: 'thailand', Population: 69800 },
  { Country: 'Timor-Leste', Slug: 'timor-leste', Population: 1318 },
  { Country: 'Togo', Slug: 'togo', Population: 8279 },
  { Country: 'Tokelau', Slug: 'tokelau', Population: 1 },
  { Country: 'Tonga', Slug: 'tonga', Population: 106 },
  { Country: 'Trinidad and Tobago', Slug: 'trinidad-and-tobago', Population: 1399 },
  { Country: 'Tunisia', Slug: 'tunisia', Population: 11819 },
  { Country: 'Turkey', Slug: 'turkey', Population: 84339 },
  { Country: 'Turkmenistan', Slug: 'turkmenistan', Population: 6031 },
  { Country: 'Turks and Caicos Islands', Slug: 'turks-and-caicos-islands', Population: 39 },
  { Country: 'Tuvalu', Slug: 'tuvalu', Population: 12 },
  { Country: 'US Minor Outlying Islands', Slug: 'us-minor-outlying-islands', Population: null },
  { Country: 'Uganda', Slug: 'uganda', Population: 45741 },
  { Country: 'Ukraine', Slug: 'ukraine', Population: 43734 },
  { Country: 'United Arab Emirates', Slug: 'united-arab-emirates', Population: 9890 },
  { Country: 'United Kingdom', Slug: 'united-kingdom', Population: 67886 },
  { Country: 'United States of America', Slug: 'united-states', Population: 331003 },
  { Country: 'Uruguay', Slug: 'uruguay', Population: 3474 },
  { Country: 'Uzbekistan', Slug: 'uzbekistan', Population: 33469 },
  { Country: 'Vanuatu', Slug: 'vanuatu', Population: 307 },
  { Country: 'Venezuela (Bolivarian Republic)', Slug: 'venezuela', Population: 28436 },
  { Country: 'Viet Nam', Slug: 'vietnam', Population: 97339 },
  { Country: 'Virgin Islands, US', Slug: 'virgin-islands', Population: null },
  { Country: 'Wallis and Futuna Islands', Slug: 'wallis-and-futuna-islands', Population: 11 },
  { Country: 'Western Sahara', Slug: 'western-sahara', Population: 597 },
  { Country: 'Yemen', Slug: 'yemen', Population: 29826 },
  { Country: 'Zambia', Slug: 'zambia', Population: 18384 },
  { Country: 'Zimbabwe', Slug: 'zimbabwe', Population: 14863 }
]